################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_comp.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_exti.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2s.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart_ex.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c \
F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c 

OBJS += \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_comp.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_cortex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_exti.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_gpio.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2s.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart_ex.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_dma.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_exti.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_gpio.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_rcc.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_usart.o \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_utils.o 

C_DEPS += \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_comp.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_cortex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_exti.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_gpio.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2s.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart_ex.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_dma.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_exti.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_gpio.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_rcc.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_usart.d \
./Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_comp.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_comp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_comp.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_cortex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_cortex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_dma_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_exti.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_exti.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_flash_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_gpio.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2c_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2s.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_i2s.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_i2s.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_pwr_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_rcc_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_spi_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_spi_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_tim_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart_ex.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_hal_usart_ex.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_hal_usart_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_dma.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_dma.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_exti.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_exti.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_exti.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_gpio.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_gpio.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_rcc.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_rcc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_usart.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_usart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_usart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_utils.o: F:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Src/stm32g0xx_ll_utils.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DSTM32G071xx -DUSE_HAL_DRIVER -DUSE_FULL_LL_DRIVER -DDEBUG -c -I../Core/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/andre/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/STM32G0xx_HAL_Driver/Inc/Legacy -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Device/ST/STM32G0xx/Include -IC:/Users/Stasy/STM32Cube/Repository/STM32Cube_FW_G0_V1.4.0/Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32G0xx_HAL_Driver/stm32g0xx_ll_utils.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

